name: Linting

on:
  push:
    paths:
      - '**.swift'
      - '.github/workflows/lint.yml'
      - '.swiftformat'
      - '.swiftlint.yml'
      - 'Mintfile'
  pull_request:
    paths:
      - '**.swift'
      - '.github/workflows/lint.yml'
      - '.swiftformat'
      - '.swiftlint.yml'
      - 'Mintfile'

jobs:
  lint:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v5

      - uses: irgaly/setup-mint@v1

      - name: Lint with SwiftFormat
        run: mint run swiftformat swiftformat --lint .

      - name: Lint with SwiftLint
        run: mint run swiftlint swiftlint lint
