name: Linting

on:
  push:
    paths: ['**.swift']
  pull_request:
    paths: ['**.swift']

jobs:
  lint-format:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v5

      - uses: irgaly/setup-mint@v1

      - name: Lint with SwiftFormat
        run: mint run swiftformat swiftformat --lint .

  lint-swiftlint:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v5

      - uses: irgaly/setup-mint@v1

      - name: Lint with SwiftLint
        run: mint run swiftlint swiftlint lint
